[project]
name = "anqi"
version = "1.0.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "TeraNovell", email = "16338782+TeraNovell@users.noreply.github.com" }
]
requires-python = ">=3.14"
dependencies = [
    "fabric==3.2.3",
]

[dependency-groups]
dev = [
    "ruff==0.16.2",
]

[tool.uv]
exclude-newer = "30 days"

[project.scripts]
anqi = "anqi.main:main"

[build-system]
requires = ["uv_build>=0.12.13,<0.13.0"]
build-backend = "uv_build"
